num1 = int(input("Informe um valor: "))
num2 = int(input("Informe outro valor: "))

print("Soma:", num1+num2)
print("Produto:", num1*num2)
print("Subtração:", num1-num2)
print("Divisão:", num1/num2)
print("Divisão inteira:", num1//num2)
print("Resto da divisão:", num1%num2)
print("Potenciação:", num1**num2)
